// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/mycelium/transactionfinder/BloomFilterArray.proto

package com.mycelium.transactionfinder;

public final class TransactionFinderProtos {
  private TransactionFinderProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BlockBloomFilterListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:transactionfinder.BlockBloomFilterList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .transactionfinder.BlockBloomFilterList.BlockBloomFilter filters = 6;</code>
     */
    java.util.List<com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter> 
        getFiltersList();
    /**
     * <code>repeated .transactionfinder.BlockBloomFilterList.BlockBloomFilter filters = 6;</code>
     */
    com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter getFilters(int index);
    /**
     * <code>repeated .transactionfinder.BlockBloomFilterList.BlockBloomFilter filters = 6;</code>
     */
    int getFiltersCount();
    /**
     * <code>repeated .transactionfinder.BlockBloomFilterList.BlockBloomFilter filters = 6;</code>
     */
    java.util.List<? extends com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilterOrBuilder> 
        getFiltersOrBuilderList();
    /**
     * <code>repeated .transactionfinder.BlockBloomFilterList.BlockBloomFilter filters = 6;</code>
     */
    com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilterOrBuilder getFiltersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code transactionfinder.BlockBloomFilterList}
   */
  public static final class BlockBloomFilterList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:transactionfinder.BlockBloomFilterList)
      BlockBloomFilterListOrBuilder {
    // Use BlockBloomFilterList.newBuilder() to construct.
    private BlockBloomFilterList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BlockBloomFilterList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BlockBloomFilterList defaultInstance;
    public static BlockBloomFilterList getDefaultInstance() {
      return defaultInstance;
    }

    public BlockBloomFilterList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BlockBloomFilterList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                filters_ = new java.util.ArrayList<com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter>();
                mutable_bitField0_ |= 0x00000001;
              }
              filters_.add(input.readMessage(com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          filters_ = java.util.Collections.unmodifiableList(filters_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mycelium.transactionfinder.TransactionFinderProtos.internal_static_transactionfinder_BlockBloomFilterList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mycelium.transactionfinder.TransactionFinderProtos.internal_static_transactionfinder_BlockBloomFilterList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.class, com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.Builder.class);
    }

    public static com.google.protobuf.Parser<BlockBloomFilterList> PARSER =
        new com.google.protobuf.AbstractParser<BlockBloomFilterList>() {
      public BlockBloomFilterList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BlockBloomFilterList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BlockBloomFilterList> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code transactionfinder.BlockBloomFilterList.HashMethod}
     */
    public enum HashMethod
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MD5 = 0;</code>
       */
      MD5(0, 0),
      ;

      /**
       * <code>MD5 = 0;</code>
       */
      public static final int MD5_VALUE = 0;


      public final int getNumber() { return value; }

      public static HashMethod valueOf(int value) {
        switch (value) {
          case 0: return MD5;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<HashMethod>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<HashMethod>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<HashMethod>() {
              public HashMethod findValueByNumber(int number) {
                return HashMethod.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.getDescriptor().getEnumTypes().get(0);
      }

      private static final HashMethod[] VALUES = values();

      public static HashMethod valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private HashMethod(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:transactionfinder.BlockBloomFilterList.HashMethod)
    }

    public interface BlockBloomFilterOrBuilder extends
        // @@protoc_insertion_point(interface_extends:transactionfinder.BlockBloomFilterList.BlockBloomFilter)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required bytes blockHash = 1;</code>
       */
      boolean hasBlockHash();
      /**
       * <code>required bytes blockHash = 1;</code>
       */
      com.google.protobuf.ByteString getBlockHash();

      /**
       * <code>required int32 size = 2;</code>
       */
      boolean hasSize();
      /**
       * <code>required int32 size = 2;</code>
       */
      int getSize();

      /**
       * <code>required int32 hashes = 3;</code>
       */
      boolean hasHashes();
      /**
       * <code>required int32 hashes = 3;</code>
       */
      int getHashes();

      /**
       * <code>required .transactionfinder.BlockBloomFilterList.HashMethod hashMethod = 4;</code>
       */
      boolean hasHashMethod();
      /**
       * <code>required .transactionfinder.BlockBloomFilterList.HashMethod hashMethod = 4;</code>
       */
      com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.HashMethod getHashMethod();

      /**
       * <code>required bytes bits = 5;</code>
       */
      boolean hasBits();
      /**
       * <code>required bytes bits = 5;</code>
       */
      com.google.protobuf.ByteString getBits();
    }
    /**
     * Protobuf type {@code transactionfinder.BlockBloomFilterList.BlockBloomFilter}
     */
    public static final class BlockBloomFilter extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:transactionfinder.BlockBloomFilterList.BlockBloomFilter)
        BlockBloomFilterOrBuilder {
      // Use BlockBloomFilter.newBuilder() to construct.
      private BlockBloomFilter(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private BlockBloomFilter(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final BlockBloomFilter defaultInstance;
      public static BlockBloomFilter getDefaultInstance() {
        return defaultInstance;
      }

      public BlockBloomFilter getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private BlockBloomFilter(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                blockHash_ = input.readBytes();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                size_ = input.readInt32();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                hashes_ = input.readInt32();
                break;
              }
              case 32: {
                int rawValue = input.readEnum();
                com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.HashMethod value = com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.HashMethod.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(4, rawValue);
                } else {
                  bitField0_ |= 0x00000008;
                  hashMethod_ = value;
                }
                break;
              }
              case 42: {
                bitField0_ |= 0x00000010;
                bits_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mycelium.transactionfinder.TransactionFinderProtos.internal_static_transactionfinder_BlockBloomFilterList_BlockBloomFilter_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mycelium.transactionfinder.TransactionFinderProtos.internal_static_transactionfinder_BlockBloomFilterList_BlockBloomFilter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter.class, com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter.Builder.class);
      }

      public static com.google.protobuf.Parser<BlockBloomFilter> PARSER =
          new com.google.protobuf.AbstractParser<BlockBloomFilter>() {
        public BlockBloomFilter parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new BlockBloomFilter(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<BlockBloomFilter> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int BLOCKHASH_FIELD_NUMBER = 1;
      private com.google.protobuf.ByteString blockHash_;
      /**
       * <code>required bytes blockHash = 1;</code>
       */
      public boolean hasBlockHash() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes blockHash = 1;</code>
       */
      public com.google.protobuf.ByteString getBlockHash() {
        return blockHash_;
      }

      public static final int SIZE_FIELD_NUMBER = 2;
      private int size_;
      /**
       * <code>required int32 size = 2;</code>
       */
      public boolean hasSize() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 size = 2;</code>
       */
      public int getSize() {
        return size_;
      }

      public static final int HASHES_FIELD_NUMBER = 3;
      private int hashes_;
      /**
       * <code>required int32 hashes = 3;</code>
       */
      public boolean hasHashes() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 hashes = 3;</code>
       */
      public int getHashes() {
        return hashes_;
      }

      public static final int HASHMETHOD_FIELD_NUMBER = 4;
      private com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.HashMethod hashMethod_;
      /**
       * <code>required .transactionfinder.BlockBloomFilterList.HashMethod hashMethod = 4;</code>
       */
      public boolean hasHashMethod() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required .transactionfinder.BlockBloomFilterList.HashMethod hashMethod = 4;</code>
       */
      public com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.HashMethod getHashMethod() {
        return hashMethod_;
      }

      public static final int BITS_FIELD_NUMBER = 5;
      private com.google.protobuf.ByteString bits_;
      /**
       * <code>required bytes bits = 5;</code>
       */
      public boolean hasBits() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bytes bits = 5;</code>
       */
      public com.google.protobuf.ByteString getBits() {
        return bits_;
      }

      private void initFields() {
        blockHash_ = com.google.protobuf.ByteString.EMPTY;
        size_ = 0;
        hashes_ = 0;
        hashMethod_ = com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.HashMethod.MD5;
        bits_ = com.google.protobuf.ByteString.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasBlockHash()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasSize()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasHashes()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasHashMethod()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasBits()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, blockHash_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, size_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt32(3, hashes_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeEnum(4, hashMethod_.getNumber());
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeBytes(5, bits_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, blockHash_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, size_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, hashes_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(4, hashMethod_.getNumber());
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(5, bits_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code transactionfinder.BlockBloomFilterList.BlockBloomFilter}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:transactionfinder.BlockBloomFilterList.BlockBloomFilter)
          com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilterOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.mycelium.transactionfinder.TransactionFinderProtos.internal_static_transactionfinder_BlockBloomFilterList_BlockBloomFilter_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.mycelium.transactionfinder.TransactionFinderProtos.internal_static_transactionfinder_BlockBloomFilterList_BlockBloomFilter_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter.class, com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter.Builder.class);
        }

        // Construct using com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          blockHash_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          size_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          hashes_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          hashMethod_ = com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.HashMethod.MD5;
          bitField0_ = (bitField0_ & ~0x00000008);
          bits_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000010);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.mycelium.transactionfinder.TransactionFinderProtos.internal_static_transactionfinder_BlockBloomFilterList_BlockBloomFilter_descriptor;
        }

        public com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter getDefaultInstanceForType() {
          return com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter.getDefaultInstance();
        }

        public com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter build() {
          com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter buildPartial() {
          com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter result = new com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.blockHash_ = blockHash_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.size_ = size_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.hashes_ = hashes_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.hashMethod_ = hashMethod_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.bits_ = bits_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter) {
            return mergeFrom((com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter other) {
          if (other == com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter.getDefaultInstance()) return this;
          if (other.hasBlockHash()) {
            setBlockHash(other.getBlockHash());
          }
          if (other.hasSize()) {
            setSize(other.getSize());
          }
          if (other.hasHashes()) {
            setHashes(other.getHashes());
          }
          if (other.hasHashMethod()) {
            setHashMethod(other.getHashMethod());
          }
          if (other.hasBits()) {
            setBits(other.getBits());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasBlockHash()) {
            
            return false;
          }
          if (!hasSize()) {
            
            return false;
          }
          if (!hasHashes()) {
            
            return false;
          }
          if (!hasHashMethod()) {
            
            return false;
          }
          if (!hasBits()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private com.google.protobuf.ByteString blockHash_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes blockHash = 1;</code>
         */
        public boolean hasBlockHash() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required bytes blockHash = 1;</code>
         */
        public com.google.protobuf.ByteString getBlockHash() {
          return blockHash_;
        }
        /**
         * <code>required bytes blockHash = 1;</code>
         */
        public Builder setBlockHash(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          blockHash_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes blockHash = 1;</code>
         */
        public Builder clearBlockHash() {
          bitField0_ = (bitField0_ & ~0x00000001);
          blockHash_ = getDefaultInstance().getBlockHash();
          onChanged();
          return this;
        }

        private int size_ ;
        /**
         * <code>required int32 size = 2;</code>
         */
        public boolean hasSize() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int32 size = 2;</code>
         */
        public int getSize() {
          return size_;
        }
        /**
         * <code>required int32 size = 2;</code>
         */
        public Builder setSize(int value) {
          bitField0_ |= 0x00000002;
          size_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 size = 2;</code>
         */
        public Builder clearSize() {
          bitField0_ = (bitField0_ & ~0x00000002);
          size_ = 0;
          onChanged();
          return this;
        }

        private int hashes_ ;
        /**
         * <code>required int32 hashes = 3;</code>
         */
        public boolean hasHashes() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required int32 hashes = 3;</code>
         */
        public int getHashes() {
          return hashes_;
        }
        /**
         * <code>required int32 hashes = 3;</code>
         */
        public Builder setHashes(int value) {
          bitField0_ |= 0x00000004;
          hashes_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 hashes = 3;</code>
         */
        public Builder clearHashes() {
          bitField0_ = (bitField0_ & ~0x00000004);
          hashes_ = 0;
          onChanged();
          return this;
        }

        private com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.HashMethod hashMethod_ = com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.HashMethod.MD5;
        /**
         * <code>required .transactionfinder.BlockBloomFilterList.HashMethod hashMethod = 4;</code>
         */
        public boolean hasHashMethod() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>required .transactionfinder.BlockBloomFilterList.HashMethod hashMethod = 4;</code>
         */
        public com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.HashMethod getHashMethod() {
          return hashMethod_;
        }
        /**
         * <code>required .transactionfinder.BlockBloomFilterList.HashMethod hashMethod = 4;</code>
         */
        public Builder setHashMethod(com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.HashMethod value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000008;
          hashMethod_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required .transactionfinder.BlockBloomFilterList.HashMethod hashMethod = 4;</code>
         */
        public Builder clearHashMethod() {
          bitField0_ = (bitField0_ & ~0x00000008);
          hashMethod_ = com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.HashMethod.MD5;
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString bits_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes bits = 5;</code>
         */
        public boolean hasBits() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>required bytes bits = 5;</code>
         */
        public com.google.protobuf.ByteString getBits() {
          return bits_;
        }
        /**
         * <code>required bytes bits = 5;</code>
         */
        public Builder setBits(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
          bits_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes bits = 5;</code>
         */
        public Builder clearBits() {
          bitField0_ = (bitField0_ & ~0x00000010);
          bits_ = getDefaultInstance().getBits();
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:transactionfinder.BlockBloomFilterList.BlockBloomFilter)
      }

      static {
        defaultInstance = new BlockBloomFilter(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:transactionfinder.BlockBloomFilterList.BlockBloomFilter)
    }

    public static final int FILTERS_FIELD_NUMBER = 6;
    private java.util.List<com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter> filters_;
    /**
     * <code>repeated .transactionfinder.BlockBloomFilterList.BlockBloomFilter filters = 6;</code>
     */
    public java.util.List<com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter> getFiltersList() {
      return filters_;
    }
    /**
     * <code>repeated .transactionfinder.BlockBloomFilterList.BlockBloomFilter filters = 6;</code>
     */
    public java.util.List<? extends com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilterOrBuilder> 
        getFiltersOrBuilderList() {
      return filters_;
    }
    /**
     * <code>repeated .transactionfinder.BlockBloomFilterList.BlockBloomFilter filters = 6;</code>
     */
    public int getFiltersCount() {
      return filters_.size();
    }
    /**
     * <code>repeated .transactionfinder.BlockBloomFilterList.BlockBloomFilter filters = 6;</code>
     */
    public com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter getFilters(int index) {
      return filters_.get(index);
    }
    /**
     * <code>repeated .transactionfinder.BlockBloomFilterList.BlockBloomFilter filters = 6;</code>
     */
    public com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilterOrBuilder getFiltersOrBuilder(
        int index) {
      return filters_.get(index);
    }

    private void initFields() {
      filters_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getFiltersCount(); i++) {
        if (!getFilters(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < filters_.size(); i++) {
        output.writeMessage(6, filters_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < filters_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, filters_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code transactionfinder.BlockBloomFilterList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:transactionfinder.BlockBloomFilterList)
        com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mycelium.transactionfinder.TransactionFinderProtos.internal_static_transactionfinder_BlockBloomFilterList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mycelium.transactionfinder.TransactionFinderProtos.internal_static_transactionfinder_BlockBloomFilterList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.class, com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.Builder.class);
      }

      // Construct using com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFiltersFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (filtersBuilder_ == null) {
          filters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          filtersBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mycelium.transactionfinder.TransactionFinderProtos.internal_static_transactionfinder_BlockBloomFilterList_descriptor;
      }

      public com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList getDefaultInstanceForType() {
        return com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.getDefaultInstance();
      }

      public com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList build() {
        com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList buildPartial() {
        com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList result = new com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList(this);
        int from_bitField0_ = bitField0_;
        if (filtersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            filters_ = java.util.Collections.unmodifiableList(filters_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.filters_ = filters_;
        } else {
          result.filters_ = filtersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList) {
          return mergeFrom((com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList other) {
        if (other == com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.getDefaultInstance()) return this;
        if (filtersBuilder_ == null) {
          if (!other.filters_.isEmpty()) {
            if (filters_.isEmpty()) {
              filters_ = other.filters_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureFiltersIsMutable();
              filters_.addAll(other.filters_);
            }
            onChanged();
          }
        } else {
          if (!other.filters_.isEmpty()) {
            if (filtersBuilder_.isEmpty()) {
              filtersBuilder_.dispose();
              filtersBuilder_ = null;
              filters_ = other.filters_;
              bitField0_ = (bitField0_ & ~0x00000001);
              filtersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFiltersFieldBuilder() : null;
            } else {
              filtersBuilder_.addAllMessages(other.filters_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getFiltersCount(); i++) {
          if (!getFilters(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter> filters_ =
        java.util.Collections.emptyList();
      private void ensureFiltersIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          filters_ = new java.util.ArrayList<com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter>(filters_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter, com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter.Builder, com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilterOrBuilder> filtersBuilder_;

      /**
       * <code>repeated .transactionfinder.BlockBloomFilterList.BlockBloomFilter filters = 6;</code>
       */
      public java.util.List<com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter> getFiltersList() {
        if (filtersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(filters_);
        } else {
          return filtersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .transactionfinder.BlockBloomFilterList.BlockBloomFilter filters = 6;</code>
       */
      public int getFiltersCount() {
        if (filtersBuilder_ == null) {
          return filters_.size();
        } else {
          return filtersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .transactionfinder.BlockBloomFilterList.BlockBloomFilter filters = 6;</code>
       */
      public com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter getFilters(int index) {
        if (filtersBuilder_ == null) {
          return filters_.get(index);
        } else {
          return filtersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .transactionfinder.BlockBloomFilterList.BlockBloomFilter filters = 6;</code>
       */
      public Builder setFilters(
          int index, com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter value) {
        if (filtersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFiltersIsMutable();
          filters_.set(index, value);
          onChanged();
        } else {
          filtersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .transactionfinder.BlockBloomFilterList.BlockBloomFilter filters = 6;</code>
       */
      public Builder setFilters(
          int index, com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter.Builder builderForValue) {
        if (filtersBuilder_ == null) {
          ensureFiltersIsMutable();
          filters_.set(index, builderForValue.build());
          onChanged();
        } else {
          filtersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .transactionfinder.BlockBloomFilterList.BlockBloomFilter filters = 6;</code>
       */
      public Builder addFilters(com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter value) {
        if (filtersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFiltersIsMutable();
          filters_.add(value);
          onChanged();
        } else {
          filtersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .transactionfinder.BlockBloomFilterList.BlockBloomFilter filters = 6;</code>
       */
      public Builder addFilters(
          int index, com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter value) {
        if (filtersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFiltersIsMutable();
          filters_.add(index, value);
          onChanged();
        } else {
          filtersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .transactionfinder.BlockBloomFilterList.BlockBloomFilter filters = 6;</code>
       */
      public Builder addFilters(
          com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter.Builder builderForValue) {
        if (filtersBuilder_ == null) {
          ensureFiltersIsMutable();
          filters_.add(builderForValue.build());
          onChanged();
        } else {
          filtersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .transactionfinder.BlockBloomFilterList.BlockBloomFilter filters = 6;</code>
       */
      public Builder addFilters(
          int index, com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter.Builder builderForValue) {
        if (filtersBuilder_ == null) {
          ensureFiltersIsMutable();
          filters_.add(index, builderForValue.build());
          onChanged();
        } else {
          filtersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .transactionfinder.BlockBloomFilterList.BlockBloomFilter filters = 6;</code>
       */
      public Builder addAllFilters(
          java.lang.Iterable<? extends com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter> values) {
        if (filtersBuilder_ == null) {
          ensureFiltersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, filters_);
          onChanged();
        } else {
          filtersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .transactionfinder.BlockBloomFilterList.BlockBloomFilter filters = 6;</code>
       */
      public Builder clearFilters() {
        if (filtersBuilder_ == null) {
          filters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          filtersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .transactionfinder.BlockBloomFilterList.BlockBloomFilter filters = 6;</code>
       */
      public Builder removeFilters(int index) {
        if (filtersBuilder_ == null) {
          ensureFiltersIsMutable();
          filters_.remove(index);
          onChanged();
        } else {
          filtersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .transactionfinder.BlockBloomFilterList.BlockBloomFilter filters = 6;</code>
       */
      public com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter.Builder getFiltersBuilder(
          int index) {
        return getFiltersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .transactionfinder.BlockBloomFilterList.BlockBloomFilter filters = 6;</code>
       */
      public com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilterOrBuilder getFiltersOrBuilder(
          int index) {
        if (filtersBuilder_ == null) {
          return filters_.get(index);  } else {
          return filtersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .transactionfinder.BlockBloomFilterList.BlockBloomFilter filters = 6;</code>
       */
      public java.util.List<? extends com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilterOrBuilder> 
           getFiltersOrBuilderList() {
        if (filtersBuilder_ != null) {
          return filtersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(filters_);
        }
      }
      /**
       * <code>repeated .transactionfinder.BlockBloomFilterList.BlockBloomFilter filters = 6;</code>
       */
      public com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter.Builder addFiltersBuilder() {
        return getFiltersFieldBuilder().addBuilder(
            com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter.getDefaultInstance());
      }
      /**
       * <code>repeated .transactionfinder.BlockBloomFilterList.BlockBloomFilter filters = 6;</code>
       */
      public com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter.Builder addFiltersBuilder(
          int index) {
        return getFiltersFieldBuilder().addBuilder(
            index, com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter.getDefaultInstance());
      }
      /**
       * <code>repeated .transactionfinder.BlockBloomFilterList.BlockBloomFilter filters = 6;</code>
       */
      public java.util.List<com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter.Builder> 
           getFiltersBuilderList() {
        return getFiltersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter, com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter.Builder, com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilterOrBuilder> 
          getFiltersFieldBuilder() {
        if (filtersBuilder_ == null) {
          filtersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter, com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilter.Builder, com.mycelium.transactionfinder.TransactionFinderProtos.BlockBloomFilterList.BlockBloomFilterOrBuilder>(
                  filters_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          filters_ = null;
        }
        return filtersBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:transactionfinder.BlockBloomFilterList)
    }

    static {
      defaultInstance = new BlockBloomFilterList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:transactionfinder.BlockBloomFilterList)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transactionfinder_BlockBloomFilterList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_transactionfinder_BlockBloomFilterList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transactionfinder_BlockBloomFilterList_BlockBloomFilter_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_transactionfinder_BlockBloomFilterList_BlockBloomFilter_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5com/mycelium/transactionfinder/BloomFi" +
      "lterArray.proto\022\021transactionfinder\"\224\002\n\024B" +
      "lockBloomFilterList\022I\n\007filters\030\006 \003(\01328.t" +
      "ransactionfinder.BlockBloomFilterList.Bl" +
      "ockBloomFilter\032\231\001\n\020BlockBloomFilter\022\021\n\tb" +
      "lockHash\030\001 \002(\014\022\014\n\004size\030\002 \002(\005\022\016\n\006hashes\030\003" +
      " \002(\005\022F\n\nhashMethod\030\004 \002(\01622.transactionfi" +
      "nder.BlockBloomFilterList.HashMethod\022\014\n\004" +
      "bits\030\005 \002(\014\"\025\n\nHashMethod\022\007\n\003MD5\020\000B9\n\036com" +
      ".mycelium.transactionfinderB\027Transaction",
      "FinderProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_transactionfinder_BlockBloomFilterList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_transactionfinder_BlockBloomFilterList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_transactionfinder_BlockBloomFilterList_descriptor,
        new java.lang.String[] { "Filters", });
    internal_static_transactionfinder_BlockBloomFilterList_BlockBloomFilter_descriptor =
      internal_static_transactionfinder_BlockBloomFilterList_descriptor.getNestedTypes().get(0);
    internal_static_transactionfinder_BlockBloomFilterList_BlockBloomFilter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_transactionfinder_BlockBloomFilterList_BlockBloomFilter_descriptor,
        new java.lang.String[] { "BlockHash", "Size", "Hashes", "HashMethod", "Bits", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
